#!/bin/bash
#
#  Script for making ATSP executables
#
BIN=../bin

cd src
echo "Making ATSP programs ..."
rm -f *.o
make

echo 
echo "Moving executables to bin/"
mv TERMS GENCL NONH PRINTW PLOTW HF MCHF BREIT CI ISO HFS $BIN/

cd ../
echo
echo "See examples from CAS in examples/CAS_book/"
echo
echo "Finished."

